name:        Zerosum Studios
markdown:    redcarpet
highlighter: pygments
paginate:    8
timezone:    America/Los_Angeles
url:         http://zerosumstudios.com
permalink:   /blog/:year/:month/:day/:title
